name: build and test

on:
  push:
    branches-ignore:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test
        run: |
          poetry run python -m pytest

  style-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task:
          - pylint sourcery_analytics/
          - mypy sourcery_analytics/
          - black --check sourcery_analytics/
          - sourcery-analytics assess sourcery_analytics/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Run checks
        run: poetry run ${{ matrix.task }}

