name: Publish

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Build and publish
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
